events {}

http {
  upstream lex_api {
    server api:8000;
  }

  server {
    listen 8080;
    client_max_body_size 50m;

    location / {
      proxy_pass http://lex_api;
      proxy_set_header Host $host;
      proxy_set_header X-Request-ID $request_id;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
